name: Waterline
options:
  bundleIdPrefix: com.waterline
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: Q2Z4UJND4C

targets:
  Waterline:
    type: application
    platform: iOS
    sources:
      - path: Waterline
    entitlements:
      path: Waterline/Waterline.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.waterline.app.shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.waterline.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_NSSupportsLiveActivities: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIRequiresFullScreen: true
        SWIFT_EMIT_LOC_STRINGS: true
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: WaterlineWidgets
      - target: WaterlineIntents
      - target: WaterlineWatch

  WaterlineWatch:
    type: application
    platform: watchOS
    sources:
      - path: WaterlineWatch
    entitlements:
      path: WaterlineWatch/WaterlineWatch.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.waterline.app.shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.waterline.app.watchkitapp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        SWIFT_EMIT_LOC_STRINGS: true
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: com.waterline.app
        INFOPLIST_KEY_WKRunsIndependentlyOfCompanionApp: false
        CODE_SIGN_STYLE: Automatic
    dependencies: []

  WaterlineWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: WaterlineWidgets
        excludes:
          - "Info.plist"
      - path: Waterline/Models.swift
      - path: Waterline/SessionActivityAttributes.swift
      - path: Waterline/WaterlineEngine.swift
      - path: WaterlineIntents/LogDrinkIntent.swift
      - path: WaterlineIntents/LogWaterIntent.swift
      - path: WaterlineIntents/StartSessionIntent.swift
      - path: WaterlineIntents/EndSessionIntent.swift
    entitlements:
      path: WaterlineWidgets/WaterlineWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.waterline.app.shared
    info:
      path: WaterlineWidgets/Info.plist
      properties:
        CFBundleDisplayName: WaterlineWidgets
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSSupportsLiveActivities: true
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.waterline.app.widgets
        SWIFT_EMIT_LOC_STRINGS: true

  WaterlineIntents:
    type: extensionkit-extension
    platform: iOS
    sources:
      - path: WaterlineIntents
        excludes:
          - "Info.plist"
      - path: Waterline/Models.swift
      - path: Waterline/SessionActivityAttributes.swift
      - path: Waterline/WaterlineEngine.swift
    entitlements:
      path: WaterlineIntents/WaterlineIntents.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.waterline.app.shared
    info:
      path: WaterlineIntents/Info.plist
      properties:
        CFBundleDisplayName: WaterlineIntents
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        EXAppExtensionAttributes:
          EXExtensionPointIdentifier: com.apple.appintents-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.waterline.app.intents
        SWIFT_EMIT_LOC_STRINGS: true

schemes:
  Waterline:
    build:
      targets:
        Waterline: all
    run:
      config: Debug
  WaterlineWatch:
    build:
      targets:
        WaterlineWatch: all
    run:
      config: Debug
